package vistas;

import java.util.List;
import javax.swing.table.DefaultTableModel;
import universidadgrupo15.accesoaDatos.*;
import universidadgrupo15.entidades.*;

public class ManejoInscripcionesView extends javax.swing.JInternalFrame {

    private DefaultTableModel tabla = new DefaultTableModel(){
        public boolean isCellEditable(int fila, int columna){
            return false;
        }
    };
    /**
     * Creates new form ManejoInscripcionesView
     */
    AlumnoData al = new AlumnoData();
    InscripcionData ind = new InscripcionData();

    public ManejoInscripcionesView() {
        initComponents();
        bGroup();
        crearCabecera();
        cargarCombo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        bgMaterias = new javax.swing.ButtonGroup();
        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jcbAlumnosInsc = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jrbMateriasInsc = new javax.swing.JRadioButton();
        jrbMateriasNoInsc = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtMaterias = new javax.swing.JTable();
        jbInscribir = new javax.swing.JButton();
        jbDesinscribir = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setClosable(true);

        panel.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Source Code Pro Semibold", 0, 14)); // NOI18N
        jLabel1.setText("Listado de Materias");

        jLabel2.setText("Seleccione un alumno:");

        jcbAlumnosInsc.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbAlumnosInscItemStateChanged(evt);
            }
        });
        jcbAlumnosInsc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcbAlumnosInscMouseClicked(evt);
            }
        });
        jcbAlumnosInsc.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
                jcbAlumnosInscCaretPositionChanged(evt);
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        jcbAlumnosInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAlumnosInscActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Source Code Pro Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Formulario de Inscripción");

        jrbMateriasInsc.setText("Materias inscriptas");
        jrbMateriasInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMateriasInscActionPerformed(evt);
            }
        });

        jrbMateriasNoInsc.setText("Materias no inscriptas");
        jrbMateriasNoInsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbMateriasNoInscActionPerformed(evt);
            }
        });

        jtMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jtMaterias);

        jbInscribir.setText("Inscribir");
        jbInscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInscribirActionPerformed(evt);
            }
        });

        jbDesinscribir.setText("Anular Inscripción");
        jbDesinscribir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDesinscribirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jrbMateriasInsc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbMateriasNoInsc)
                .addGap(95, 95, 95))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(jbInscribir)
                        .addGap(82, 82, 82)
                        .addComponent(jbDesinscribir)
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39)
                        .addComponent(jcbAlumnosInsc, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
            .addGroup(panelLayout.createSequentialGroup()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel1))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel3))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(9, 9, 9)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jcbAlumnosInsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbMateriasInsc)
                    .addComponent(jrbMateriasNoInsc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInscribir)
                    .addComponent(jbDesinscribir))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbMateriasInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMateriasInscActionPerformed
        // TODO add your handling code here:
        
        listarMaterias(true);
    }//GEN-LAST:event_jrbMateriasInscActionPerformed

    private void jrbMateriasNoInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbMateriasNoInscActionPerformed
        // TODO add your handling code here:

        listarMaterias(false);
    }//GEN-LAST:event_jrbMateriasNoInscActionPerformed

    private void jbInscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInscribirActionPerformed
        // TODO add your handling code here:
        int matSelec = jtMaterias.getSelectedRow();
        if (matSelec != -1) {
            Inscripcion inscripcion = new Inscripcion();
            Alumno alumno = (Alumno) jcbAlumnosInsc.getSelectedItem();
            Materia materia = new Materia();
            materia.setIdMateria((Integer) jtMaterias.getValueAt(matSelec, 0));
            materia.setNombre((String) jtMaterias.getValueAt(matSelec, 1));
            materia.setAño((Integer) jtMaterias.getValueAt(matSelec, 2));

            inscripcion.setAlumno(alumno);
            inscripcion.setMateria(materia);

            ind.guardarInscripcion(inscripcion);
        }
        listarMaterias(false);
    }//GEN-LAST:event_jbInscribirActionPerformed

    private void jbDesinscribirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDesinscribirActionPerformed
        // TODO add your handling code here:
        int matSelec = jtMaterias.getSelectedRow();
        if (matSelec != -1) {
            Alumno al = (Alumno) jcbAlumnosInsc.getSelectedItem();
            int idMat=(Integer) jtMaterias.getValueAt(matSelec, 0);
            ind.borrarInscripcionMateriaAlumno(al.getIdAlumno(), idMat);
        }
        listarMaterias(true);
    }//GEN-LAST:event_jbDesinscribirActionPerformed

    private void jcbAlumnosInscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAlumnosInscActionPerformed
        // TODO add your handling code here:
        limpiarTabla();
    }//GEN-LAST:event_jcbAlumnosInscActionPerformed

    private void jcbAlumnosInscMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcbAlumnosInscMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbAlumnosInscMouseClicked

    private void jcbAlumnosInscItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbAlumnosInscItemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jcbAlumnosInscItemStateChanged

    private void jcbAlumnosInscCaretPositionChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jcbAlumnosInscCaretPositionChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jcbAlumnosInscCaretPositionChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bgMaterias;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbDesinscribir;
    private javax.swing.JButton jbInscribir;
    private javax.swing.JComboBox<Alumno> jcbAlumnosInsc;
    private javax.swing.JRadioButton jrbMateriasInsc;
    private javax.swing.JRadioButton jrbMateriasNoInsc;
    private javax.swing.JTable jtMaterias;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables

    
    private void cargarCombo() {
        List<Alumno> alumnos = al.ListarAlumnos();
        for (Alumno alum : alumnos) {

            jcbAlumnosInsc.addItem(alum);
        }
    }

    private void bGroup() {
        bgMaterias.add(jrbMateriasInsc);
        bgMaterias.add(jrbMateriasNoInsc);
    }
    
    private void crearCabecera() {
        tabla.addColumn("ID");
        tabla.addColumn("Nombre");
        tabla.addColumn("Año");
        jtMaterias.setModel(tabla);
    }

    private void limpiarTabla() {
        int f = jtMaterias.getRowCount()-1;
        
        for(;f>=0;f--){
            tabla.removeRow(f);
        }
    }
    
    private void listarMaterias(boolean cursadas){
        limpiarTabla();
        Alumno alumno = (Alumno) jcbAlumnosInsc.getSelectedItem();
        List<Materia> materias;
        if(cursadas){
            materias = ind.obtenerMateriasCursadas(alumno.getIdAlumno());
        } else {
            materias = ind.obtenerMateriasNoCursadas(alumno.getIdAlumno());
        }
        
        for (Materia m : materias) {
            tabla.addRow(new Object[]{m.getIdMateria(), m.getNombre(), m.getAño()});
        }
    }

}
